services:
  postgres:
    image: postgres:16
    container_name: air_sensor_psql
    hostname: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: air_sensor_db
    command: [ 'postgres', '-c', 'wal_level=logical' ]
    healthcheck:
      test: ['CMD', 'psql', '-U', 'postgres', '-c', 'SELECT 1']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - air_sensor_net

networks:
  air_sensor_net:
    name: air_sensor_net
    driver: bridge